version: '3.9'
services:
  redis:
    image: redis:alpine
    container_name: redis
    command: redis-server --requirepass ${REDIS_PASS}
    environment:
      - REDIS_PASSWORD=${REDIS_PASS}
    ports:
      - "6379:6379"
    restart: always
  mongodb:
    image: mongo:latest
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=shorturl
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
    ports:
      - "27018:27017"
    volumes:
      - ./data:/data/db
    restart: always


